/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package working.with.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Maksim
 */
public class EditNumber extends javax.swing.JFrame {

    private Connection conn = null;
    private UserNumber number;
    private PhoneDirectory frmPhoneDirectory;
    private ViewNumbers frmViewNumbers;
    /**
     * Creates new form EditNumber
     */
    public EditNumber(PhoneDirectory frmPhoneDirectory, ViewNumbers frmViewNumbers) {
        initComponents();
        conn = ConnectorWithDatabase.getConn();
        this.frmPhoneDirectory = frmPhoneDirectory;
        this.frmViewNumbers = frmViewNumbers;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        txtNumber = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();

        setTitle("Змінити номер");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlBackground.setBackground(new java.awt.Color(153, 255, 153));

        txtNumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        btnEdit.setBackground(new java.awt.Color(0, 204, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEdit.setText("Змінити");
        btnEdit.setBorderPainted(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if(txtNumber.getText().length() > 15){
            JOptionPane.showMessageDialog(rootPane, "Номер телефону не може бути більшим за 15 символів", "Помилка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(editNumber()){
            frmPhoneDirectory.setEnabled(true);
            frmViewNumbers.downloadNumbers();
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frmPhoneDirectory.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    public void setUserNumber(UserNumber number){
        this.number = number;
        txtNumber.setText(number.toString());
    }
    
    public boolean editNumber(){
        String SQL = "UPDATE user_numbers SET phone = ? WHERE id = " + number.getId();
        PreparedStatement st = null;
        try{
            st = conn.prepareStatement(SQL);
            st.setString(1, txtNumber.getText());
        } catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Помилка під час встановлення з'єднання з базою даних","Помилка",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try{
            int rez = st.executeUpdate();
            if(rez == 1){
                return true;
            }
            return false;
        } catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Не вдалося змінити номер","Помилка",JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
