/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package working.with.db;

import java.awt.Component;
import working.with.db.autorization.Autorization;

/**
 *
 * @author Maksim
 */
public class PhoneDirectory extends javax.swing.JFrame {

    private static User user;
    
    private CreateNumber frmCreateNumber;
    private ViewNumbers frmViewNumbers;
    private CreateContactToNumber frmCreateContactToNumber;
    private ViewContacts frmViewContacts;
    /**
     * Creates new form PhoneDirectory
     */
    public PhoneDirectory() {
        if(ConnectorWithDatabase.doConnect()){
            initComponents();
            login();
        } else {
            System.exit(0);
        }
    }

    public void login(){
        Autorization frmAutorization = new Autorization(this);
        frmAutorization.setVisible(true);
    }
    
    public void hideDesctopPaneComponents(){
        for(Component component: dsctp.getComponents()){
            component.setVisible(false);
        }
        pnlView.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnViewNumbers = new javax.swing.JButton();
        btnCreateNumber = new javax.swing.JButton();
        btnViewContacts = new javax.swing.JButton();
        btnCreateContact = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        dsctp = new javax.swing.JDesktopPane();
        pnlView = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(204, 204, 255));

        pnlMenu.setBackground(new java.awt.Color(153, 153, 255));

        btnViewNumbers.setBackground(new java.awt.Color(0, 51, 255));
        btnViewNumbers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewNumbers.setForeground(new java.awt.Color(255, 255, 255));
        btnViewNumbers.setText("Переглянути номери");
        btnViewNumbers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNumbersActionPerformed(evt);
            }
        });

        btnCreateNumber.setBackground(new java.awt.Color(0, 51, 255));
        btnCreateNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateNumber.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateNumber.setText("Додати номер");
        btnCreateNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNumberActionPerformed(evt);
            }
        });

        btnViewContacts.setBackground(new java.awt.Color(0, 51, 255));
        btnViewContacts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewContacts.setForeground(new java.awt.Color(255, 255, 255));
        btnViewContacts.setText("Переглянути контакти");
        btnViewContacts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewContacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewContactsActionPerformed(evt);
            }
        });

        btnCreateContact.setBackground(new java.awt.Color(0, 51, 255));
        btnCreateContact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateContact.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateContact.setText("Додати контакт до номеру");
        btnCreateContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateContactActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(0, 51, 255));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Головна");
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 51, 255));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Вихід");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnViewNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCreateContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnViewContacts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCreateNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnCreateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnViewNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCreateContact, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnViewContacts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlView.setBackground(new java.awt.Color(204, 204, 255));

        lblName.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        lblName.setForeground(new java.awt.Color(51, 0, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Телефонний довідник");

        lblAuthor.setForeground(new java.awt.Color(0, 0, 153));
        lblAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthor.setText("Виконав: Студент групи КН-33, Росоха Максим Валентинович");

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
            .addComponent(lblAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );

        dsctp.setLayer(pnlView, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dsctpLayout = new javax.swing.GroupLayout(dsctp);
        dsctp.setLayout(dsctpLayout);
        dsctpLayout.setHorizontalGroup(
            dsctpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dsctpLayout.setVerticalGroup(
            dsctpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dsctp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dsctp)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNumberActionPerformed
        hideDesctopPaneComponents();
        if(frmCreateNumber == null){
            frmCreateNumber = new CreateNumber();
            dsctp.add(frmCreateNumber);
            frmCreateNumber.setSize(dsctp.getWidth(), dsctp.getHeight());
        }
        frmCreateNumber.setVisible(true);
    }//GEN-LAST:event_btnCreateNumberActionPerformed

    private void btnViewNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNumbersActionPerformed
        hideDesctopPaneComponents();
        if(frmViewNumbers == null){
            frmViewNumbers = new ViewNumbers(this);
            dsctp.add(frmViewNumbers);
            frmViewNumbers.setSize(dsctp.getWidth(), dsctp.getHeight());
        }
        frmViewNumbers.downloadNumbers();
        frmViewNumbers.setVisible(true);
    }//GEN-LAST:event_btnViewNumbersActionPerformed

    private void btnCreateContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateContactActionPerformed
        hideDesctopPaneComponents();
        if(frmCreateContactToNumber == null){
            frmCreateContactToNumber = new CreateContactToNumber();
            dsctp.add(frmCreateContactToNumber);
            frmCreateContactToNumber.setSize(dsctp.getWidth(), dsctp.getHeight());
        }
        frmCreateContactToNumber.downloadNumbers();
        frmCreateContactToNumber.setVisible(true);
    }//GEN-LAST:event_btnCreateContactActionPerformed

    private void btnViewContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewContactsActionPerformed
        hideDesctopPaneComponents();
        if(frmViewContacts == null){
            frmViewContacts = new ViewContacts(this);
            dsctp.add(frmViewContacts);
            frmViewContacts.setSize(dsctp.getWidth(), dsctp.getHeight());
        }
        frmViewContacts.downloadNumbers();
        frmViewContacts.setVisible(true);
    }//GEN-LAST:event_btnViewContactsActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        hideDesctopPaneComponents();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhoneDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhoneDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhoneDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhoneDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhoneDirectory().setVisible(false);
            }
        });
    }
    
    public static User getUser() {
        return user;
    }

    public static void setUser(User user) {
        PhoneDirectory.user = user;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateContact;
    private javax.swing.JButton btnCreateNumber;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnViewContacts;
    private javax.swing.JButton btnViewNumbers;
    private javax.swing.JDesktopPane dsctp;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlView;
    // End of variables declaration//GEN-END:variables
}
