/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package working.with.db;

import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Maksim
 */
public class ViewNumbers extends javax.swing.JInternalFrame {

    private Connection conn = null;
    private List<UserNumber> numbers = new ArrayList<>();
    private EditNumber frmEditNumber;
    private PhoneDirectory frmPhoneDirectory;
    
    /**
     * Creates new form ViewNumbers
     */
    public ViewNumbers(PhoneDirectory frmPhoneDirectory) {
        initComponents();
        conn = ConnectorWithDatabase.getConn();
        this.frmPhoneDirectory = frmPhoneDirectory;
    }
    
    public void downloadNumbers(){
        String SQL = "SELECT id, phone FROM user_numbers WHERE id_user = " + PhoneDirectory.getUser().getId();
        PreparedStatement st = null;
        
        try{
            st = conn.prepareStatement(SQL);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Помилка під час встановлення з'єднання з базою даних","Помилка",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            ResultSet rez = st.executeQuery();
            cmbNumbers.removeAllItems();
            if(!rez.isBeforeFirst()){
                btnEdit.setEnabled(false);
                btnDelete.setEnabled(false);
                JOptionPane.showMessageDialog(rootPane,"У вас немає доданих номерів");
                return;
            }
            
            while(rez.next()){
                numbers.add(new UserNumber(rez.getInt("id"), rez.getString("phone")));
                cmbNumbers.addItem(rez.getString("phone"));
            }
            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            
        }catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Не вдалося завантажити номери з бази даних","Помилка",JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        cmbNumbers = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Перегляд телефонів");

        pnlBackground.setBackground(new java.awt.Color(204, 204, 255));

        cmbNumbers.setBackground(new java.awt.Color(0, 0, 255));
        cmbNumbers.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        btnEdit.setBackground(new java.awt.Color(0, 255, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEdit.setText("Змінити");
        btnEdit.setBorderPainted(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDelete.setText("Видалити");
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(cmbNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        UserNumber number = null;
        for(UserNumber num: numbers){
            if(cmbNumbers.getSelectedItem().equals(num.getNumber())){
                number = num;
                break;
            }
        }
        if(frmEditNumber == null){
            frmEditNumber = new EditNumber(frmPhoneDirectory, this);
        }
        frmEditNumber.setUserNumber(number);
        frmEditNumber.setVisible(true);
        frmPhoneDirectory.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        UserNumber number = null;
        for(UserNumber num: numbers){
            if(cmbNumbers.getSelectedItem().equals(num.getNumber())){
                number = num;
                break;
            }
        }
        
        if(deleteNumber(number)){
            downloadNumbers();
            JOptionPane.showMessageDialog(rootPane,"Номер успішно видалений");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private boolean deleteNumber(UserNumber number){
        String SQL = "DELETE FROM user_numbers WHERE id = " + number.getId();
        PreparedStatement st = null;
        try{
            st = conn.prepareStatement(SQL);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Помилка під час встановлення з'єднання з базою даних","Помилка",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try{
            int rez = st.executeUpdate();
            if(rez == 1){
                return true;
            }
            return false;
        } catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Не вдалося видалити номер","Помилка",JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cmbNumbers;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
