/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package working.with.db.autorization;

import java.sql.*;
import javax.swing.JOptionPane;
import working.with.db.ConnectorWithDatabase;
import working.with.db.PhoneDirectory;
import working.with.db.User;

/**
 *
 * @author Maksim
 */
public class Registration extends javax.swing.JFrame implements AbleToAuthorization {

    private Connection conn;
    private User user;
    private PhoneDirectory frmPhoneDirectory;

    /**
     * Creates new form Registration
     */
    public Registration(PhoneDirectory frmPhoneDirectory) {
        initComponents();
        conn = ConnectorWithDatabase.getConn();
        this.frmPhoneDirectory = frmPhoneDirectory;
    }

    public User getUser() {
        return user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblRegistration = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Реєстрація");
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(255, 102, 255));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnLogin.setBackground(new java.awt.Color(153, 0, 204));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Зареєструватися");
        btnLogin.setBorderPainted(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Пароль:");

        txtLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblRegistration.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistration.setText("Логін:");

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(txtPassword))
                    .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(lblRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(!checkData()){
            return;
        }
        if(!CheckLoginForUniqueness()){
            return;
        }
        if(!registration()){
            return;
        }
        user = new User(getIdForUser(),txtLogin.getText());
        this.setVisible(false);
        frmPhoneDirectory.setVisible(true);
        PhoneDirectory.setUser(user);
    }//GEN-LAST:event_btnLoginActionPerformed

    
    private boolean checkData(){
        if(txtLogin.getText().length() > 30){
            JOptionPane.showMessageDialog(null,"Кількість символів логіну не повинна перевищувати 30");
            return false;
        }
        if(txtLogin.getText().length() < 3){
            JOptionPane.showMessageDialog(null,"Кількість символів логіну не повинна бути меншою за 3");
            return false;
        }
        if(txtPassword.getText().length() > 30){
            JOptionPane.showMessageDialog(null,"Кількість символів пароля не повинна перевищувати 30");
            return false;
        }
        if(txtPassword.getText().length() < 3){
            JOptionPane.showMessageDialog(null,"Кількість символів пароля не повинна бути меншою за 3");
            return false;
        }
        return true;
    }
    
    private boolean CheckLoginForUniqueness(){
        String SQL= "SELECT login FROM `users` WHERE `login`=?";
        PreparedStatement st = null;
        try {
            st = conn.prepareStatement(SQL);
            st.setString(1, txtLogin.getText());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Помилка під час встановлення з’єднання з базою даних" ,"Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try {
            ResultSet rez=st.executeQuery();
            if(!rez.isBeforeFirst()) {
                return true;
            } 
            JOptionPane.showMessageDialog(null, "Логін \"" + txtLogin.getText() + "\" вже існує" ,"Error",JOptionPane.ERROR_MESSAGE);
            return false;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Помилка під час встановлення з’єднання з базою даних" ,"Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private boolean registration(){
        String SQL = "INSERT INTO users (login, password) VALUES (?,?)";
        PreparedStatement st = null;
        
        try{
            st = conn.prepareStatement(SQL);
            st.setString(1, txtLogin.getText());
            st.setString(2, hashPassword(txtPassword.getText()));
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Помилка під час встановлення з'єднання з базою даних");
            return false;
        }
        try{
            int rez = st.executeUpdate();
            if(rez == 1){
                return true;
            }
            return false;
        } catch (SQLException ex){
            return false;
        }
    }
    
    private int getIdForUser(){
        String SQL = "SELECT id FROM users WHERE login = ?;";
        PreparedStatement st = null;
        
        try{
            st = conn.prepareStatement(SQL);
            st.setString(1, txtLogin.getText());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Помилка під час встановлення з'єднання з базою даних");
            return 0;
        }
        try{
            ResultSet rez = st.executeQuery();
            if(rez.next()){
                return rez.getInt("id");
            }
            return 0;
        } catch (SQLException ex){
            return 0;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
